accounts:
  - name: alice
    coins: ["1000000000000000uusd", "1000000stake"]
  - name: bob
    coins: ["1000000uusd"]
validator:
  name: alice
  staked: "1000000stake"
genesis:
  chain_id: "goldentrade"
  app_state:
    learncosmos:
      gold_amount: "1000000"
servers:
  api-address: "localhost:1317"
  rpc-address: "localhost:26657"
