// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: learncosmos/query.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGoldPoolRequest struct {
}

func (m *QueryGoldPoolRequest) Reset()         { *m = QueryGoldPoolRequest{} }
func (m *QueryGoldPoolRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGoldPoolRequest) ProtoMessage()    {}
func (*QueryGoldPoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab2052da1b96eba, []int{0}
}
func (m *QueryGoldPoolRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGoldPoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGoldPoolRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGoldPoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGoldPoolRequest.Merge(m, src)
}
func (m *QueryGoldPoolRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGoldPoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGoldPoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGoldPoolRequest proto.InternalMessageInfo

// this line is used by starport scaffolding # 3
type QueryGoldPoolResponse struct {
	GoldAmount uint64 `protobuf:"varint,1,opt,name=gold_amount,json=goldAmount,proto3" json:"gold_amount,omitempty"`
}

func (m *QueryGoldPoolResponse) Reset()         { *m = QueryGoldPoolResponse{} }
func (m *QueryGoldPoolResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGoldPoolResponse) ProtoMessage()    {}
func (*QueryGoldPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab2052da1b96eba, []int{1}
}
func (m *QueryGoldPoolResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGoldPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGoldPoolResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGoldPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGoldPoolResponse.Merge(m, src)
}
func (m *QueryGoldPoolResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGoldPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGoldPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGoldPoolResponse proto.InternalMessageInfo

func (m *QueryGoldPoolResponse) GetGoldAmount() uint64 {
	if m != nil {
		return m.GoldAmount
	}
	return 0
}

type QueryOwnedGoldRequest struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *QueryOwnedGoldRequest) Reset()         { *m = QueryOwnedGoldRequest{} }
func (m *QueryOwnedGoldRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOwnedGoldRequest) ProtoMessage()    {}
func (*QueryOwnedGoldRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab2052da1b96eba, []int{2}
}
func (m *QueryOwnedGoldRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOwnedGoldRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOwnedGoldRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOwnedGoldRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOwnedGoldRequest.Merge(m, src)
}
func (m *QueryOwnedGoldRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryOwnedGoldRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOwnedGoldRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOwnedGoldRequest proto.InternalMessageInfo

func (m *QueryOwnedGoldRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type QueryOwnedGoldResponse struct {
	Amount uint64 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *QueryOwnedGoldResponse) Reset()         { *m = QueryOwnedGoldResponse{} }
func (m *QueryOwnedGoldResponse) String() string { return proto.CompactTextString(m) }
func (*QueryOwnedGoldResponse) ProtoMessage()    {}
func (*QueryOwnedGoldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab2052da1b96eba, []int{3}
}
func (m *QueryOwnedGoldResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOwnedGoldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOwnedGoldResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOwnedGoldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOwnedGoldResponse.Merge(m, src)
}
func (m *QueryOwnedGoldResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryOwnedGoldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOwnedGoldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOwnedGoldResponse proto.InternalMessageInfo

func (m *QueryOwnedGoldResponse) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type QueryPoolOrderRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryPoolOrderRequest) Reset()         { *m = QueryPoolOrderRequest{} }
func (m *QueryPoolOrderRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPoolOrderRequest) ProtoMessage()    {}
func (*QueryPoolOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab2052da1b96eba, []int{4}
}
func (m *QueryPoolOrderRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPoolOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPoolOrderRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPoolOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPoolOrderRequest.Merge(m, src)
}
func (m *QueryPoolOrderRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPoolOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPoolOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPoolOrderRequest proto.InternalMessageInfo

func (m *QueryPoolOrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryPoolOrderResponse struct {
	Id           string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type         OrderType   `protobuf:"varint,2,opt,name=type,proto3,enum=ntchjb.learncosmos.learncosmos.OrderType" json:"type,omitempty"`
	UserAddr     string      `protobuf:"bytes,3,opt,name=user_addr,json=userAddr,proto3" json:"user_addr,omitempty"`
	PricePerUnit uint64      `protobuf:"varint,4,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	Amount       uint64      `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Status       OrderStatus `protobuf:"varint,6,opt,name=status,proto3,enum=ntchjb.learncosmos.learncosmos.OrderStatus" json:"status,omitempty"`
	StatusReason string      `protobuf:"bytes,7,opt,name=status_reason,json=statusReason,proto3" json:"status_reason,omitempty"`
}

func (m *QueryPoolOrderResponse) Reset()         { *m = QueryPoolOrderResponse{} }
func (m *QueryPoolOrderResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPoolOrderResponse) ProtoMessage()    {}
func (*QueryPoolOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab2052da1b96eba, []int{5}
}
func (m *QueryPoolOrderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPoolOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPoolOrderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPoolOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPoolOrderResponse.Merge(m, src)
}
func (m *QueryPoolOrderResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPoolOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPoolOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPoolOrderResponse proto.InternalMessageInfo

func (m *QueryPoolOrderResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueryPoolOrderResponse) GetType() OrderType {
	if m != nil {
		return m.Type
	}
	return OrderType_BUY
}

func (m *QueryPoolOrderResponse) GetUserAddr() string {
	if m != nil {
		return m.UserAddr
	}
	return ""
}

func (m *QueryPoolOrderResponse) GetPricePerUnit() uint64 {
	if m != nil {
		return m.PricePerUnit
	}
	return 0
}

func (m *QueryPoolOrderResponse) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *QueryPoolOrderResponse) GetStatus() OrderStatus {
	if m != nil {
		return m.Status
	}
	return OrderStatus_PENDING
}

func (m *QueryPoolOrderResponse) GetStatusReason() string {
	if m != nil {
		return m.StatusReason
	}
	return ""
}

func init() {
	proto.RegisterType((*QueryGoldPoolRequest)(nil), "ntchjb.learncosmos.learncosmos.QueryGoldPoolRequest")
	proto.RegisterType((*QueryGoldPoolResponse)(nil), "ntchjb.learncosmos.learncosmos.QueryGoldPoolResponse")
	proto.RegisterType((*QueryOwnedGoldRequest)(nil), "ntchjb.learncosmos.learncosmos.QueryOwnedGoldRequest")
	proto.RegisterType((*QueryOwnedGoldResponse)(nil), "ntchjb.learncosmos.learncosmos.QueryOwnedGoldResponse")
	proto.RegisterType((*QueryPoolOrderRequest)(nil), "ntchjb.learncosmos.learncosmos.QueryPoolOrderRequest")
	proto.RegisterType((*QueryPoolOrderResponse)(nil), "ntchjb.learncosmos.learncosmos.QueryPoolOrderResponse")
}

func init() { proto.RegisterFile("learncosmos/query.proto", fileDescriptor_5ab2052da1b96eba) }

var fileDescriptor_5ab2052da1b96eba = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xcd, 0x6e, 0xd3, 0x30,
	0x1c, 0x5f, 0xb2, 0xb6, 0xac, 0x66, 0x54, 0xc8, 0x2a, 0x25, 0x64, 0x28, 0x8c, 0x80, 0xc4, 0x10,
	0x6a, 0x82, 0xca, 0x87, 0xb8, 0x70, 0x18, 0x1c, 0xb8, 0x20, 0x6d, 0x04, 0xb8, 0x70, 0x89, 0xd2,
	0xda, 0xea, 0x82, 0x52, 0x3b, 0xb3, 0x1d, 0x8d, 0x6a, 0xda, 0x85, 0x27, 0xe0, 0xe3, 0xcc, 0x1b,
	0xf0, 0x20, 0x1c, 0x2b, 0x71, 0xe1, 0x88, 0x5a, 0x1e, 0x04, 0xf9, 0x1f, 0x17, 0x85, 0x80, 0xa0,
	0xbb, 0xd9, 0x3f, 0xfb, 0xf7, 0x61, 0xfb, 0x27, 0xa3, 0x8b, 0x19, 0x4d, 0x04, 0x1b, 0x71, 0x39,
	0xe1, 0x32, 0x3c, 0x2c, 0xa8, 0x98, 0x06, 0xb9, 0xe0, 0x8a, 0x63, 0x8f, 0xa9, 0xd1, 0xc1, 0xeb,
	0x61, 0x50, 0x59, 0xaf, 0x8e, 0xdd, 0xcb, 0x63, 0xce, 0xc7, 0x19, 0x0d, 0x93, 0x3c, 0x0d, 0x13,
	0xc6, 0xb8, 0x4a, 0x54, 0xca, 0x99, 0x2c, 0xd9, 0x6e, 0xaf, 0x2a, 0x3b, 0xe6, 0x19, 0x29, 0x71,
	0xbf, 0x87, 0xba, 0xcf, 0xb4, 0xc9, 0x13, 0x9e, 0x91, 0x7d, 0xce, 0xb3, 0x88, 0x1e, 0x16, 0x54,
	0x2a, 0xff, 0x01, 0xba, 0x50, 0xc3, 0x65, 0xce, 0x99, 0xa4, 0xf8, 0x0a, 0x3a, 0xab, 0xe9, 0x71,
	0x32, 0xe1, 0x05, 0x53, 0x8e, 0xb5, 0x6d, 0xed, 0x34, 0x22, 0xa4, 0xa1, 0x5d, 0x40, 0xfc, 0xbe,
	0x61, 0xee, 0x1d, 0x31, 0x4a, 0x34, 0xdd, 0x48, 0xe2, 0x2e, 0x6a, 0xf2, 0x23, 0x46, 0x05, 0x70,
	0xda, 0x51, 0x39, 0xf1, 0x6f, 0xa3, 0x5e, 0x7d, 0xbb, 0x71, 0xea, 0xa1, 0xd6, 0x6f, 0x26, 0x66,
	0xe6, 0xdf, 0x30, 0x06, 0x3a, 0xd6, 0x9e, 0x20, 0x54, 0x2c, 0x0d, 0x3a, 0xc8, 0x4e, 0x89, 0x51,
	0xb7, 0x53, 0xe2, 0x7f, 0xb6, 0x8d, 0x76, 0x65, 0xa7, 0xd1, 0xae, 0x6d, 0xc5, 0x0f, 0x51, 0x43,
	0x4d, 0x73, 0xea, 0xd8, 0xdb, 0xd6, 0x4e, 0x67, 0x70, 0x33, 0xf8, 0xf7, 0x5d, 0x07, 0x20, 0xf6,
	0x62, 0x9a, 0xd3, 0x08, 0x68, 0x78, 0x0b, 0xb5, 0x0b, 0x49, 0x45, 0x9c, 0x10, 0x22, 0x9c, 0x75,
	0x50, 0xdd, 0xd0, 0xc0, 0x2e, 0x21, 0x02, 0x5f, 0x47, 0x9d, 0x5c, 0xa4, 0x23, 0x1a, 0xe7, 0x54,
	0xc4, 0x05, 0x4b, 0x95, 0xd3, 0x80, 0xf3, 0x6c, 0x02, 0xba, 0x4f, 0xc5, 0x4b, 0x96, 0xaa, 0xca,
	0x69, 0x9b, 0xd5, 0xd3, 0xe2, 0xc7, 0xa8, 0x25, 0x55, 0xa2, 0x0a, 0xe9, 0xb4, 0x20, 0xdb, 0xad,
	0x95, 0xb2, 0x3d, 0x07, 0x4a, 0x64, 0xa8, 0xf8, 0x1a, 0x3a, 0x57, 0x8e, 0x62, 0x41, 0x13, 0xc9,
	0x99, 0x73, 0x06, 0x32, 0x6e, 0x96, 0x60, 0x04, 0xd8, 0x60, 0xb6, 0x8e, 0x9a, 0x70, 0x5d, 0xf8,
	0xbd, 0x85, 0x36, 0x96, 0x0f, 0x8f, 0xef, 0xfe, 0xcf, 0xf0, 0x6f, 0xfd, 0x71, 0xef, 0x9d, 0x92,
	0x55, 0xbe, 0x8b, 0xef, 0xbc, 0xfd, 0xfa, 0xe3, 0xa3, 0x8d, 0xf1, 0xf9, 0xb2, 0xfa, 0xd0, 0xd4,
	0x7e, 0xae, 0x63, 0x7c, 0xb2, 0x50, 0xfb, 0x57, 0x47, 0xf0, 0x6a, 0xf2, 0xf5, 0x0a, 0xba, 0xf7,
	0x4f, 0x4b, 0x33, 0xb1, 0xae, 0x42, 0xac, 0x2d, 0x7c, 0xc9, 0xc4, 0xd2, 0xd5, 0x25, 0x7d, 0x1d,
	0x2e, 0x3c, 0x86, 0x1a, 0x9f, 0xe0, 0x0f, 0x16, 0x6a, 0xc2, 0xd5, 0xaf, 0x98, 0xad, 0xde, 0xde,
	0x15, 0xb3, 0xfd, 0x51, 0x65, 0xdf, 0x85, 0x6c, 0x5d, 0x8c, 0x97, 0xd9, 0xf4, 0xaa, 0x0c, 0x8f,
	0x53, 0x72, 0xf2, 0xe8, 0xe9, 0x97, 0xb9, 0x67, 0xcd, 0xe6, 0x9e, 0xf5, 0x7d, 0xee, 0x59, 0xef,
	0x16, 0xde, 0xda, 0x6c, 0xe1, 0xad, 0x7d, 0x5b, 0x78, 0x6b, 0xaf, 0x06, 0xe3, 0x54, 0x1d, 0x14,
	0xc3, 0x60, 0xc4, 0x27, 0x61, 0xe9, 0x1b, 0x82, 0x57, 0xdf, 0x7c, 0x11, 0x6f, 0xc2, 0xea, 0x87,
	0xa1, 0x4b, 0x2e, 0x87, 0x2d, 0xf8, 0x32, 0xee, 0xfc, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xa7, 0x08,
	0xb0, 0xbf, 0xa3, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// this line is used by starport scaffolding # 2
	GoldPool(ctx context.Context, in *QueryGoldPoolRequest, opts ...grpc.CallOption) (*QueryGoldPoolResponse, error)
	OwnedGold(ctx context.Context, in *QueryOwnedGoldRequest, opts ...grpc.CallOption) (*QueryOwnedGoldResponse, error)
	Order(ctx context.Context, in *QueryPoolOrderRequest, opts ...grpc.CallOption) (*QueryPoolOrderResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GoldPool(ctx context.Context, in *QueryGoldPoolRequest, opts ...grpc.CallOption) (*QueryGoldPoolResponse, error) {
	out := new(QueryGoldPoolResponse)
	err := c.cc.Invoke(ctx, "/ntchjb.learncosmos.learncosmos.Query/GoldPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OwnedGold(ctx context.Context, in *QueryOwnedGoldRequest, opts ...grpc.CallOption) (*QueryOwnedGoldResponse, error) {
	out := new(QueryOwnedGoldResponse)
	err := c.cc.Invoke(ctx, "/ntchjb.learncosmos.learncosmos.Query/OwnedGold", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Order(ctx context.Context, in *QueryPoolOrderRequest, opts ...grpc.CallOption) (*QueryPoolOrderResponse, error) {
	out := new(QueryPoolOrderResponse)
	err := c.cc.Invoke(ctx, "/ntchjb.learncosmos.learncosmos.Query/Order", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// this line is used by starport scaffolding # 2
	GoldPool(context.Context, *QueryGoldPoolRequest) (*QueryGoldPoolResponse, error)
	OwnedGold(context.Context, *QueryOwnedGoldRequest) (*QueryOwnedGoldResponse, error)
	Order(context.Context, *QueryPoolOrderRequest) (*QueryPoolOrderResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GoldPool(ctx context.Context, req *QueryGoldPoolRequest) (*QueryGoldPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoldPool not implemented")
}
func (*UnimplementedQueryServer) OwnedGold(ctx context.Context, req *QueryOwnedGoldRequest) (*QueryOwnedGoldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OwnedGold not implemented")
}
func (*UnimplementedQueryServer) Order(ctx context.Context, req *QueryPoolOrderRequest) (*QueryPoolOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Order not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GoldPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGoldPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GoldPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ntchjb.learncosmos.learncosmos.Query/GoldPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GoldPool(ctx, req.(*QueryGoldPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OwnedGold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOwnedGoldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OwnedGold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ntchjb.learncosmos.learncosmos.Query/OwnedGold",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OwnedGold(ctx, req.(*QueryOwnedGoldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Order_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPoolOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Order(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ntchjb.learncosmos.learncosmos.Query/Order",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Order(ctx, req.(*QueryPoolOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ntchjb.learncosmos.learncosmos.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GoldPool",
			Handler:    _Query_GoldPool_Handler,
		},
		{
			MethodName: "OwnedGold",
			Handler:    _Query_OwnedGold_Handler,
		},
		{
			MethodName: "Order",
			Handler:    _Query_Order_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "learncosmos/query.proto",
}

func (m *QueryGoldPoolRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGoldPoolRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGoldPoolRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGoldPoolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGoldPoolResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGoldPoolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.GoldAmount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.GoldAmount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryOwnedGoldRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOwnedGoldRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOwnedGoldRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryOwnedGoldResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOwnedGoldResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOwnedGoldResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryPoolOrderRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPoolOrderRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPoolOrderRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryPoolOrderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPoolOrderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPoolOrderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StatusReason) > 0 {
		i -= len(m.StatusReason)
		copy(dAtA[i:], m.StatusReason)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.StatusReason)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Status != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x30
	}
	if m.Amount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x28
	}
	if m.PricePerUnit != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PricePerUnit))
		i--
		dAtA[i] = 0x20
	}
	if len(m.UserAddr) > 0 {
		i -= len(m.UserAddr)
		copy(dAtA[i:], m.UserAddr)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.UserAddr)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Type != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGoldPoolRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGoldPoolResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.GoldAmount != 0 {
		n += 1 + sovQuery(uint64(m.GoldAmount))
	}
	return n
}

func (m *QueryOwnedGoldRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryOwnedGoldResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Amount != 0 {
		n += 1 + sovQuery(uint64(m.Amount))
	}
	return n
}

func (m *QueryPoolOrderRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPoolOrderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovQuery(uint64(m.Type))
	}
	l = len(m.UserAddr)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.PricePerUnit != 0 {
		n += 1 + sovQuery(uint64(m.PricePerUnit))
	}
	if m.Amount != 0 {
		n += 1 + sovQuery(uint64(m.Amount))
	}
	if m.Status != 0 {
		n += 1 + sovQuery(uint64(m.Status))
	}
	l = len(m.StatusReason)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGoldPoolRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGoldPoolRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGoldPoolRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGoldPoolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGoldPoolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGoldPoolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GoldAmount", wireType)
			}
			m.GoldAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GoldAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOwnedGoldRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOwnedGoldRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOwnedGoldRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOwnedGoldResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOwnedGoldResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOwnedGoldResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPoolOrderRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPoolOrderRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPoolOrderRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPoolOrderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPoolOrderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPoolOrderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= OrderType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PricePerUnit", wireType)
			}
			m.PricePerUnit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PricePerUnit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= OrderStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StatusReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StatusReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
