// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: learncosmos/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/x/ibc/core/04-channel/types"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgBuyGold struct {
	Buyer          string `protobuf:"bytes,1,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Amount         uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	IbcChannel     string `protobuf:"bytes,3,opt,name=ibc_channel,json=ibcChannel,proto3" json:"ibc_channel,omitempty"`
	OracleScriptId int64  `protobuf:"varint,4,opt,name=oracle_script_id,json=oracleScriptId,proto3" json:"oracle_script_id,omitempty"`
}

func (m *MsgBuyGold) Reset()         { *m = MsgBuyGold{} }
func (m *MsgBuyGold) String() string { return proto.CompactTextString(m) }
func (*MsgBuyGold) ProtoMessage()    {}
func (*MsgBuyGold) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d05de96db97a9dd, []int{0}
}
func (m *MsgBuyGold) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBuyGold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBuyGold.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBuyGold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBuyGold.Merge(m, src)
}
func (m *MsgBuyGold) XXX_Size() int {
	return m.Size()
}
func (m *MsgBuyGold) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBuyGold.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBuyGold proto.InternalMessageInfo

func (m *MsgBuyGold) GetBuyer() string {
	if m != nil {
		return m.Buyer
	}
	return ""
}

func (m *MsgBuyGold) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *MsgBuyGold) GetIbcChannel() string {
	if m != nil {
		return m.IbcChannel
	}
	return ""
}

func (m *MsgBuyGold) GetOracleScriptId() int64 {
	if m != nil {
		return m.OracleScriptId
	}
	return 0
}

type MsgBuyGoldResponse struct {
}

func (m *MsgBuyGoldResponse) Reset()         { *m = MsgBuyGoldResponse{} }
func (m *MsgBuyGoldResponse) String() string { return proto.CompactTextString(m) }
func (*MsgBuyGoldResponse) ProtoMessage()    {}
func (*MsgBuyGoldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d05de96db97a9dd, []int{1}
}
func (m *MsgBuyGoldResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgBuyGoldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgBuyGoldResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgBuyGoldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBuyGoldResponse.Merge(m, src)
}
func (m *MsgBuyGoldResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgBuyGoldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBuyGoldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBuyGoldResponse proto.InternalMessageInfo

type MsgSellGold struct {
	Seller         string `protobuf:"bytes,1,opt,name=seller,proto3" json:"seller,omitempty"`
	Amount         uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	IbcChannel     string `protobuf:"bytes,3,opt,name=ibc_channel,json=ibcChannel,proto3" json:"ibc_channel,omitempty"`
	OracleScriptId int64  `protobuf:"varint,4,opt,name=oracle_script_id,json=oracleScriptId,proto3" json:"oracle_script_id,omitempty"`
}

func (m *MsgSellGold) Reset()         { *m = MsgSellGold{} }
func (m *MsgSellGold) String() string { return proto.CompactTextString(m) }
func (*MsgSellGold) ProtoMessage()    {}
func (*MsgSellGold) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d05de96db97a9dd, []int{2}
}
func (m *MsgSellGold) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSellGold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSellGold.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSellGold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSellGold.Merge(m, src)
}
func (m *MsgSellGold) XXX_Size() int {
	return m.Size()
}
func (m *MsgSellGold) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSellGold.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSellGold proto.InternalMessageInfo

func (m *MsgSellGold) GetSeller() string {
	if m != nil {
		return m.Seller
	}
	return ""
}

func (m *MsgSellGold) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *MsgSellGold) GetIbcChannel() string {
	if m != nil {
		return m.IbcChannel
	}
	return ""
}

func (m *MsgSellGold) GetOracleScriptId() int64 {
	if m != nil {
		return m.OracleScriptId
	}
	return 0
}

type MsgSellGoldResponse struct {
}

func (m *MsgSellGoldResponse) Reset()         { *m = MsgSellGoldResponse{} }
func (m *MsgSellGoldResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSellGoldResponse) ProtoMessage()    {}
func (*MsgSellGoldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d05de96db97a9dd, []int{3}
}
func (m *MsgSellGoldResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSellGoldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSellGoldResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSellGoldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSellGoldResponse.Merge(m, src)
}
func (m *MsgSellGoldResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSellGoldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSellGoldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSellGoldResponse proto.InternalMessageInfo

type MsgTransferGold struct {
	Sender   string `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver string `protobuf:"bytes,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount   uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgTransferGold) Reset()         { *m = MsgTransferGold{} }
func (m *MsgTransferGold) String() string { return proto.CompactTextString(m) }
func (*MsgTransferGold) ProtoMessage()    {}
func (*MsgTransferGold) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d05de96db97a9dd, []int{4}
}
func (m *MsgTransferGold) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferGold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferGold.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferGold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferGold.Merge(m, src)
}
func (m *MsgTransferGold) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferGold) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferGold.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferGold proto.InternalMessageInfo

func (m *MsgTransferGold) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgTransferGold) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *MsgTransferGold) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type MsgTransferGoldResponse struct {
}

func (m *MsgTransferGoldResponse) Reset()         { *m = MsgTransferGoldResponse{} }
func (m *MsgTransferGoldResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTransferGoldResponse) ProtoMessage()    {}
func (*MsgTransferGoldResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d05de96db97a9dd, []int{5}
}
func (m *MsgTransferGoldResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferGoldResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferGoldResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferGoldResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferGoldResponse.Merge(m, src)
}
func (m *MsgTransferGoldResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferGoldResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferGoldResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferGoldResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgBuyGold)(nil), "ntchjb.learncosmos.learncosmos.MsgBuyGold")
	proto.RegisterType((*MsgBuyGoldResponse)(nil), "ntchjb.learncosmos.learncosmos.MsgBuyGoldResponse")
	proto.RegisterType((*MsgSellGold)(nil), "ntchjb.learncosmos.learncosmos.MsgSellGold")
	proto.RegisterType((*MsgSellGoldResponse)(nil), "ntchjb.learncosmos.learncosmos.MsgSellGoldResponse")
	proto.RegisterType((*MsgTransferGold)(nil), "ntchjb.learncosmos.learncosmos.MsgTransferGold")
	proto.RegisterType((*MsgTransferGoldResponse)(nil), "ntchjb.learncosmos.learncosmos.MsgTransferGoldResponse")
}

func init() { proto.RegisterFile("learncosmos/tx.proto", fileDescriptor_9d05de96db97a9dd) }

var fileDescriptor_9d05de96db97a9dd = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0x3f, 0x8f, 0xd3, 0x30,
	0x18, 0xc6, 0xeb, 0xcb, 0x51, 0xee, 0xde, 0x43, 0x80, 0x4c, 0x39, 0x42, 0x84, 0x42, 0x95, 0x29,
	0x02, 0x11, 0x8b, 0xde, 0xc0, 0x7e, 0x0c, 0x08, 0x89, 0x2c, 0x39, 0x26, 0x24, 0x54, 0x25, 0x8e,
	0x49, 0x8d, 0x5c, 0x3b, 0xb2, 0x93, 0x53, 0xfb, 0x01, 0x90, 0x18, 0xf9, 0x58, 0x8c, 0x1d, 0x3b,
	0xa2, 0xf6, 0x8b, 0x20, 0xf2, 0xaf, 0x29, 0x03, 0x6a, 0x17, 0xb6, 0x3e, 0x6f, 0xdf, 0xe7, 0x79,
	0x7f, 0xb6, 0xf3, 0xc2, 0x48, 0xb0, 0x58, 0x4b, 0xaa, 0xcc, 0x5c, 0x19, 0x52, 0x2c, 0x82, 0x5c,
	0xab, 0x42, 0x61, 0x57, 0x16, 0x74, 0xf6, 0x35, 0x09, 0x7a, 0x7f, 0xf6, 0x7f, 0x3b, 0xcf, 0x78,
	0x42, 0x09, 0x55, 0x9a, 0x11, 0x3a, 0x8b, 0xa5, 0x64, 0x82, 0xdc, 0xbe, 0xee, 0xdc, 0xde, 0x37,
	0x04, 0x10, 0x9a, 0xec, 0xba, 0x5c, 0xbe, 0x53, 0x22, 0xc5, 0x23, 0xb8, 0x93, 0x94, 0x4b, 0xa6,
	0x6d, 0x34, 0x46, 0xfe, 0x79, 0x54, 0x0b, 0x7c, 0x09, 0xc3, 0x78, 0xae, 0x4a, 0x59, 0xd8, 0x27,
	0x63, 0xe4, 0x9f, 0x46, 0x8d, 0xc2, 0xcf, 0xe1, 0x82, 0x27, 0x74, 0xda, 0xe4, 0xda, 0x56, 0xe5,
	0x01, 0x9e, 0xd0, 0xb7, 0x75, 0x05, 0xfb, 0xf0, 0x50, 0xe9, 0x98, 0x0a, 0x36, 0x35, 0x54, 0xf3,
	0xbc, 0x98, 0xf2, 0xd4, 0x3e, 0x1d, 0x23, 0xdf, 0x8a, 0xee, 0xd7, 0xf5, 0x9b, 0xaa, 0xfc, 0x3e,
	0xf5, 0x46, 0x80, 0x77, 0x18, 0x11, 0x33, 0xb9, 0x92, 0x86, 0x79, 0xdf, 0x11, 0x5c, 0x84, 0x26,
	0xbb, 0x61, 0x42, 0x54, 0x78, 0x97, 0x30, 0x34, 0x4c, 0x88, 0x8e, 0xaf, 0x51, 0xff, 0x03, 0xf0,
	0x31, 0x3c, 0xea, 0x91, 0x74, 0x84, 0x9f, 0xe1, 0x41, 0x68, 0xb2, 0x8f, 0x3a, 0x96, 0xe6, 0x0b,
	0xd3, 0x3b, 0x48, 0x99, 0xf6, 0x21, 0xff, 0x28, 0xec, 0xc0, 0x99, 0x66, 0x94, 0xf1, 0x5b, 0xa6,
	0x2b, 0xcc, 0xf3, 0xa8, 0xd3, 0xbd, 0x03, 0x58, 0xfd, 0x03, 0x78, 0x4f, 0xe1, 0xc9, 0x5f, 0xf1,
	0xed, 0xe4, 0xc9, 0xfa, 0x04, 0xac, 0xd0, 0x64, 0x98, 0xc3, 0xdd, 0xf6, 0xf5, 0x5e, 0x04, 0xff,
	0xfe, 0x16, 0x82, 0xdd, 0x15, 0x3b, 0x93, 0xc3, 0x7b, 0xdb, 0x91, 0x58, 0xc0, 0x59, 0xf7, 0x14,
	0x2f, 0x0f, 0xf0, 0xb7, 0xcd, 0xce, 0xd5, 0x11, 0xcd, 0xdd, 0xb4, 0x05, 0xdc, 0xdb, 0xbb, 0x57,
	0x72, 0x40, 0x48, 0xdf, 0xe0, 0xbc, 0x39, 0xd2, 0xd0, 0x4e, 0xbe, 0xfe, 0xf0, 0x73, 0xe3, 0xa2,
	0xd5, 0xc6, 0x45, 0xbf, 0x36, 0x2e, 0xfa, 0xb1, 0x75, 0x07, 0xab, 0xad, 0x3b, 0x58, 0x6f, 0xdd,
	0xc1, 0xa7, 0x49, 0xc6, 0x8b, 0x59, 0x99, 0x04, 0x54, 0xcd, 0x49, 0x1d, 0x4e, 0xaa, 0xc0, 0x57,
	0xcd, 0x56, 0x2e, 0xc8, 0xde, 0x8e, 0x2e, 0x73, 0x66, 0x92, 0x61, 0xb5, 0x69, 0x57, 0xbf, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xaa, 0x1f, 0x92, 0x3a, 0xbf, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	BuyGold(ctx context.Context, in *MsgBuyGold, opts ...grpc.CallOption) (*MsgBuyGoldResponse, error)
	SellGold(ctx context.Context, in *MsgSellGold, opts ...grpc.CallOption) (*MsgSellGoldResponse, error)
	TransferGold(ctx context.Context, in *MsgTransferGold, opts ...grpc.CallOption) (*MsgTransferGoldResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) BuyGold(ctx context.Context, in *MsgBuyGold, opts ...grpc.CallOption) (*MsgBuyGoldResponse, error) {
	out := new(MsgBuyGoldResponse)
	err := c.cc.Invoke(ctx, "/ntchjb.learncosmos.learncosmos.Msg/BuyGold", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SellGold(ctx context.Context, in *MsgSellGold, opts ...grpc.CallOption) (*MsgSellGoldResponse, error) {
	out := new(MsgSellGoldResponse)
	err := c.cc.Invoke(ctx, "/ntchjb.learncosmos.learncosmos.Msg/SellGold", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TransferGold(ctx context.Context, in *MsgTransferGold, opts ...grpc.CallOption) (*MsgTransferGoldResponse, error) {
	out := new(MsgTransferGoldResponse)
	err := c.cc.Invoke(ctx, "/ntchjb.learncosmos.learncosmos.Msg/TransferGold", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	BuyGold(context.Context, *MsgBuyGold) (*MsgBuyGoldResponse, error)
	SellGold(context.Context, *MsgSellGold) (*MsgSellGoldResponse, error)
	TransferGold(context.Context, *MsgTransferGold) (*MsgTransferGoldResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) BuyGold(ctx context.Context, req *MsgBuyGold) (*MsgBuyGoldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyGold not implemented")
}
func (*UnimplementedMsgServer) SellGold(ctx context.Context, req *MsgSellGold) (*MsgSellGoldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SellGold not implemented")
}
func (*UnimplementedMsgServer) TransferGold(ctx context.Context, req *MsgTransferGold) (*MsgTransferGoldResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferGold not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_BuyGold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBuyGold)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).BuyGold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ntchjb.learncosmos.learncosmos.Msg/BuyGold",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).BuyGold(ctx, req.(*MsgBuyGold))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SellGold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSellGold)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SellGold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ntchjb.learncosmos.learncosmos.Msg/SellGold",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SellGold(ctx, req.(*MsgSellGold))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TransferGold_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransferGold)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferGold(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ntchjb.learncosmos.learncosmos.Msg/TransferGold",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferGold(ctx, req.(*MsgTransferGold))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ntchjb.learncosmos.learncosmos.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BuyGold",
			Handler:    _Msg_BuyGold_Handler,
		},
		{
			MethodName: "SellGold",
			Handler:    _Msg_SellGold_Handler,
		},
		{
			MethodName: "TransferGold",
			Handler:    _Msg_TransferGold_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "learncosmos/tx.proto",
}

func (m *MsgBuyGold) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBuyGold) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBuyGold) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OracleScriptId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.OracleScriptId))
		i--
		dAtA[i] = 0x20
	}
	if len(m.IbcChannel) > 0 {
		i -= len(m.IbcChannel)
		copy(dAtA[i:], m.IbcChannel)
		i = encodeVarintTx(dAtA, i, uint64(len(m.IbcChannel)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Amount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Buyer) > 0 {
		i -= len(m.Buyer)
		copy(dAtA[i:], m.Buyer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Buyer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgBuyGoldResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgBuyGoldResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgBuyGoldResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSellGold) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSellGold) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSellGold) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OracleScriptId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.OracleScriptId))
		i--
		dAtA[i] = 0x20
	}
	if len(m.IbcChannel) > 0 {
		i -= len(m.IbcChannel)
		copy(dAtA[i:], m.IbcChannel)
		i = encodeVarintTx(dAtA, i, uint64(len(m.IbcChannel)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Amount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Seller) > 0 {
		i -= len(m.Seller)
		copy(dAtA[i:], m.Seller)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Seller)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSellGoldResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSellGoldResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSellGoldResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgTransferGold) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferGold) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferGold) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTransferGoldResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferGoldResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferGoldResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgBuyGold) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Buyer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovTx(uint64(m.Amount))
	}
	l = len(m.IbcChannel)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.OracleScriptId != 0 {
		n += 1 + sovTx(uint64(m.OracleScriptId))
	}
	return n
}

func (m *MsgBuyGoldResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSellGold) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Seller)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovTx(uint64(m.Amount))
	}
	l = len(m.IbcChannel)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.OracleScriptId != 0 {
		n += 1 + sovTx(uint64(m.OracleScriptId))
	}
	return n
}

func (m *MsgSellGoldResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgTransferGold) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovTx(uint64(m.Amount))
	}
	return n
}

func (m *MsgTransferGoldResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgBuyGold) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBuyGold: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBuyGold: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buyer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Buyer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleScriptId", wireType)
			}
			m.OracleScriptId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OracleScriptId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgBuyGoldResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgBuyGoldResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgBuyGoldResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSellGold) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSellGold: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSellGold: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seller", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Seller = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleScriptId", wireType)
			}
			m.OracleScriptId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OracleScriptId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSellGoldResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSellGoldResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSellGoldResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferGold) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferGold: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferGold: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferGoldResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferGoldResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferGoldResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
